name: 'Static Analysis and Testing'

on:
  pull_request:

jobs:
  analyzer:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: flutter analyze

  formatter:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: flutter format --output=none --set-exit-if-changed .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: flutter test --coverage
